using System.Collections;
using System.Collections.Frozen;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Text;
using RecursiveParsing.Parse;
using RecursiveParsing.Tokenize;

namespace RecursiveParsing.Visitors;

// https://c9x.me/compile/

public sealed class QBEVisitor(Dictionary<(Token, ImmutableArray<ExpressionTypeUnion>), (ExpressionTypeUnion type, string funcName)> functions) : Visitor
{
    private readonly FrozenDictionary<(Token, ImmutableArray<ExpressionTypeUnion>), (ExpressionTypeUnion type, string funcName)> _functionsSignature = [with(new FunctionEquality()), ..functions];
    sealed class FunctionEquality : IEqualityComparer<(Token, ImmutableArray<ExpressionTypeUnion>)>
    {
        public bool Equals((Token, ImmutableArray<ExpressionTypeUnion>) x, (Token, ImmutableArray<ExpressionTypeUnion>) y)
        => x.Item1 == y.Item1 && x.Item2.SequenceEqual(y.Item2);

        public int GetHashCode([DisallowNull] (Token, ImmutableArray<ExpressionTypeUnion>) obj)
        => HashCode.Combine(obj.Item1, ((IStructuralEquatable)obj.Item2).GetHashCode(new ImmutableArrayEquality()));

        sealed class ImmutableArrayEquality : System.Collections.IEqualityComparer
        {
            public new bool Equals(object? x, object? y)
            => (x, y) is (ExpressionTypeUnion l, ExpressionTypeUnion r) ? l == r : throw new Exception();

            public int GetHashCode(object obj)
            => obj is ExpressionTypeUnion t ? t.GetHashCode() : throw new Exception();
        }
    }

    public StringBuilder QBEFile { get; } = new();
    private readonly StringBuilder _QBEDatas = new();
    private readonly StringBuilder _QBEFunctions = new();
    private readonly HashSet<string> _functionWrapper = [];

    private readonly Stack<int> _ifsSteps = [];
    private readonly Stack<string> _switchLabels = [];

    private int _varCount = 0;
    private int _strCount = 0;

    public override void Enter(Parse.File file)
    {
        Debug.Assert(_varCount == 0);
        // https://stackoverflow.com/a/22114373/5830999 bool for `printf` format
        QBEFile.AppendLine(System.IO.File.ReadAllText("Visitors/runtime.ssa"))
        .AppendLine($$"""
        data $_main_return_value = { w 0 }

        export function w $main() {
        @start
            call $__setup_bool_specifier()
            call $_srand()
        """);
    }

    public override void Exit(Parse.File file)
    {
        Debug.Assert(_varCount == 0);
        Debug.Assert(_ifsSteps is { Count: 0 });
        Debug.Assert(_switchLabels is { Count: 0 });
        QBEFile.AppendLine($$"""
            %_main_return_value =w loadw $_main_return_value
            ret %_main_return_value
        }
        """)
        .AppendLine()
        .AppendLine("# Autogenerated:")
        .Append(_QBEDatas)
        .AppendLine()
        .Append(_QBEFunctions);
    }

    public override void Exit(CallExpr callExpr)
    {
        var args = GetTypes(callExpr.Args);
        var callName = GenerateCall(callExpr.Type, args);
        var length = callExpr.Args.Length + 1;
        Debug.Assert(_varCount >= length);
        QBEFile.AppendLine($$"""    {{(callExpr.Type is ExpressionType.None ? "" : $"%_w{_varCount - length} =w ")}}call {{callName}}({{string.Join(", ", args.Prepend(ExpressionType.Function).Select(a => $"{TypeToQBE(a)} %_{TypeToQBE(a)}{_varCount - length--}"))}})""");
        _varCount -= callExpr.Args.Length - (callExpr.Type is ExpressionType.None ? 0 : 1) + 1;

        static ImmutableArray<ExpressionTypeUnion> GetTypes(ImmutableArray<Expression> expressions)
        => [..expressions.Select(e => e.Type)];

        string GenerateCall(ExpressionTypeUnion ret, ImmutableArray<ExpressionTypeUnion> args)
        {
            if (ret is ExpressionType.None)
            {
                var name = $"$_call_n";
                if (args is [])
                {
                    if (_functionWrapper.Add(name))
                        _QBEFunctions.AppendLine($$"""
                        function {{name}}(l %fun) {
                        @start
                            call %fun()
                            ret
                        }
                        """);
                    return name;
                }
                name += '_' + string.Concat(args.Select(TypeToQBE));
                if (_functionWrapper.Add(name))
                {
                    string v = string.Join(", ", args.Select((a, i) => TypeToQBE(a) + " %arg" + i));
                    _QBEFunctions.AppendLine($$"""
                    function {{name}}(l %fun, {{v}}) {
                    @start
                        call %fun({{v}})
                        ret
                    }
                    """);
                }
                return name;
            }
            else
            {
                var v1 = TypeToQBE(ret);
                var name = $"$_call_" + v1;
                if (args is [])
                {
                    if (_functionWrapper.Add(name))
                        _QBEFunctions.AppendLine($$"""
                        function {{v1}} {{name}}(l %fun) {
                        @start
                            %ret ={{v1}} call %fun()
                            ret %ret
                        }
                        """);
                    return name;
                }
                name += '_' + string.Concat(args.Select(TypeToQBE));
                if (_functionWrapper.Add(name))
                {
                    string v = string.Join(", ", args.Select((a, i) => TypeToQBE(a) + " %arg" + i));
                    _QBEFunctions.AppendLine($$"""
                    function {{v1}} {{name}}(l %fun, {{v}}) {
                    @start
                        %ret ={{v1}} call %fun({{v}})
                        ret %ret
                    }
                    """);
                }
                return name;
            }
        }
    }

    public override void Exit(BinaryExpr binaryExpr)
    {
        Debug.Assert(_varCount >= 2);
#pragma warning disable CS8846 // The switch expression does not handle all possible values of its input type (it is not exhaustive).
        _ = binaryExpr.Signatures switch
#pragma warning restore CS8846 // The switch expression does not handle all possible values of its input type (it is not exhaustive).
        {
            { Length: not 1 } or [{ Args.Length: not 2 }] => throw new UnreachableException(),
            [{ Return: var ret, Args: [var lhs, var rhs] } sig] when FunctionNameFromSignature(binaryExpr.Operator.Token, sig) is var name and ['_', ..] => QBEFile.AppendLine($$"""    %_{{TypeToQBE(ret)}}{{_varCount - 2}} ={{TypeToQBE(ret)}} call ${{name}}({{TypeToQBE(lhs)}} %_{{TypeToQBE(lhs)}}{{_varCount - 2}}, {{TypeToQBE(rhs)}} %_{{TypeToQBE(rhs)}}{{_varCount - 1}})"""),
            [{ Return: var ret, Args: [var lhs, var rhs] } sig] when FunctionNameFromSignature(binaryExpr.Operator.Token, sig) is var name => QBEFile.AppendLine($$"""    %_{{TypeToQBE(ret)}}{{_varCount - 2}} ={{TypeToQBE(ret)}} {{name}} %_{{TypeToQBE(lhs)}}{{_varCount - 2}}, %_{{TypeToQBE(rhs)}}{{_varCount - 1}}"""),
        };
        _varCount -= 1;
    }

    public override void Enter(IfStatement ifStatement)
    {
        _ifsSteps.Push(ifStatement.Else is null ? 0b01 : 0b11);
    }

    public override void Visit(IfStatement ifStatement)
    {
        var step = _ifsSteps.Pop();
        var (lbl_true, lbl_false, lbl_cont) = ($"@true_if_{ifStatement.GetHashCode() :X}", $"@false_if_{ifStatement.GetHashCode() :X}", $"@continue_if_{ifStatement.GetHashCode() :X}");
        if ((step & 0b01) != 0) // between condition and then
        {
            Debug.Assert(_varCount >= 1);
            QBEFile.AppendLine($$"""
                jnz %_w{{_varCount - 1}}, {{lbl_true}}, {{ ((step & 0b10) != 0 ? lbl_false : lbl_cont)}}
            {{lbl_true}}
            """);
            _varCount -= 1;
            _ifsSteps.Push(step ^ 0b01);
        }
        else if ((step & 0b10) != 0) // between then and else
        {
            QBEFile.AppendLine($$"""
                jmp {{lbl_cont}}
            {{lbl_false}}
            """);
            _ifsSteps.Push(step ^ 0b10);
        }
        else throw new UnreachableException();
    }

    public override void Exit(IfStatement ifStatement)
    {
        var lbl_cont = $"@continue_if_{ifStatement.GetHashCode() :X}";
        QBEFile.AppendLine($$"""
        {{lbl_cont}}
        """);
        if (_ifsSteps.Pop() != 0b00)
            throw new UnreachableException();
    }

    public override void Enter(SwitchStatement switchStatement)
    {
        _switchLabels.Push($"@continue_switch_{switchStatement.GetHashCode() :X}");
    }

    public override void Visit(SwitchCase switchCase)
    {
        Debug.Assert(_varCount >= 2);
        var (lbl_case, lbl_cont, type) = ($"@case_switch_{switchCase.GetHashCode() :X}", $"@continue_switch_{switchCase.GetHashCode() :X}", TypeToQBE(switchCase.Expression.Type));
        QBEFile.AppendLine(switchCase.Expression.Type switch
        {
            _ when FunctionNameFromSignature(new Token.Symbol("=="), new(ExpressionType.Bool, [switchCase.Expression.Type, switchCase.Expression.Type])) is var name and ['_', ..] => $$"""    %_w{{_varCount - 1}} =w call ${{name}}({{type}} %_{{type}}{{_varCount - 2}}, {{type}} %_{{type}}{{_varCount - 1}})""",
            _ when FunctionNameFromSignature(new Token.Symbol("=="), new(ExpressionType.Bool, [switchCase.Expression.Type, switchCase.Expression.Type])) is var name => $$"""    %_w{{_varCount - 1}} =w {{name}} %_{{type}}{{_varCount - 2}}, %_{{type}}{{_varCount - 1}}""",
            _ => throw new UnreachableException(),
        }).AppendLine($$"""
            jnz %_w{{_varCount - 1}}, {{lbl_case}}, {{lbl_cont}}
        {{lbl_case}}
        """);
        _varCount -= 1;
    }

    public override void Exit(SwitchCase switchCase)
    {
        QBEFile.AppendLine($$"""
            jmp {{_switchLabels.Peek()}}
        @continue_switch_{{switchCase.GetHashCode() :X}}
        """);
    }

    public override void Exit(SwitchStatement switchStatement)
    {
        QBEFile.AppendLine($$"""{{_switchLabels.Pop()}}""");
        _varCount -= 1;
    }

    static char TypeToQBE(ExpressionTypeUnion type)
    => type switch
    {
        ImmutableArray<FunctionSignature> { Length: 1 } or ExpressionType.String or ExpressionType.Function => 'l',
        ExpressionType.Bool or ExpressionType.Int => 'w',
        ExpressionType or ImmutableArray<FunctionSignature> or null => throw new UnreachableException(),
    };

    public override void Exit(PrefixExpr prefixExpr)
    {
        Debug.Assert(_varCount >= 1);
        switch (prefixExpr.Operator.Token)
        {
            case Token.Symbol { Value: "+" }:
                break;
            case Token.Symbol { Value: "-" }:
                QBEFile.AppendLine($$"""    %_w{{_varCount - 1}} =w neg %_w{{_varCount - 1}}""");
                break;
            case Token.Symbol { Value: "!" }:
                QBEFile.AppendLine($$"""    %_w{{_varCount - 1}} =w sub 1, %_w{{_varCount - 1}}""");
                break;
            default: throw new UnreachableException();
        }
    }

    public override void Exit(TernaryExpr ternaryExpr)
    {
        switch (ternaryExpr.OpLeft.Token, ternaryExpr.OpRight.Token)
        {
            case (Token.Symbol { Value: "?" }, Token.Symbol { Value: ":" }):
            {
                Debug.Assert(_varCount >= 3);
                var (lbl_true, lbl_false, lbl_cont, type) = ($"@true_conditionnal_{ternaryExpr.GetHashCode() :X}", $"@false_conditionnal_{ternaryExpr.GetHashCode() :X}", $"@continue_conditionnal_{ternaryExpr.GetHashCode() :X}", TypeToQBE(ternaryExpr.Type));
                QBEFile.AppendLine($$"""
                    jnz %_w{{_varCount - 3}}, {{lbl_true}}, {{lbl_false}}
                {{lbl_true}}
                    %_{{type}}{{_varCount - 3}} ={{type}} copy %_{{type}}{{_varCount - 2}}
                    jmp {{lbl_cont}}
                {{lbl_false}}
                    %_{{type}}{{_varCount - 3}} ={{type}} copy %_{{type}}{{_varCount - 1}}
                {{lbl_cont}}
                """);
                _varCount -= 2;
                break;
            }
            default: throw new UnreachableException();
        }
    }

    public override void Visit(Primary primary)
    {
        switch (primary.TokenSpan.Token)
        {
            case Token.String { Value: string s }:
                QBEFile.AppendLine($$"""    %_l{{_varCount}} =l copy $str_{{_strCount}}""");
                _QBEDatas.AppendLine($$"""data $str_{{_strCount++}} = { b "{{s}}", b 0 }""");
                _varCount += 1;
                break;
            case Token.Id { Value: "true" }:
                QBEFile.AppendLine($$"""    %_w{{_varCount}} =w copy 1""");
                _varCount += 1;
                break;
            case Token.Id { Value: "false" }:
                QBEFile.AppendLine($$"""    %_w{{_varCount}} =w copy 0""");
                _varCount += 1;
                break;
            case Token.Id id when primary.Type is ImmutableArray<FunctionSignature> { Length: 1 } sig:
                QBEFile.AppendLine($$"""    %_l{{_varCount}} =l copy ${{FunctionNameFromSignature(id, sig[0])}}""");
                _varCount += 1;
                break;
            case Token.Int { Value: int i }:
                QBEFile.AppendLine($$"""    %_w{{_varCount}} =w copy {{i}}""");
                _varCount += 1;
                break;
            default: throw new UnreachableException();
        }
    }

    private string FunctionNameFromSignature(Token name, FunctionSignature signature)
    {
        if (_functionsSignature.TryGetValue((name, signature.Args), out var infos) && signature.Return == infos.type)
            return infos.funcName;
        throw new UnreachableException();
    }
}
